<?
if($bln==1){
$nabul="Januari";
}elseif($bln==2){
$nabul="Februari";
}elseif($bln==3){
$nabul="Maret";
}elseif($bln==4){
$nabul="April";
}elseif($bln==5){
$nabul="Mei";
}elseif($bln==6){
$nabul="Juni";
}elseif($bln==7){
$nabul="Juli";
}elseif($bln==8){
$nabul="Agustus";
}elseif($bln==9){
$nabul="September";
}elseif($bln==10){
$nabul="Oktober";
}elseif($bln==11){
$nabul="November";
}elseif($bln==12){
$nabul="Desember";
}else{
$nabul="?";
}
echo " $nabul $thn1";
 ?>